### ISSUE TITLE
REGISTRATION REDIRECTION

### ISSUE THREAD

**Issue by markarsanious** [SEGUC17/Drop-The-Bit#21]
Severity: Medium
Reported By: Mark Isaac
Description: Upon successful completion of registration, it redirects to the home page as a signed in user directly without logging in.
Steps to release the issue: home>>Signup>>Ok
Expected: It should redirect to the login page not login automatically.

**Comment by habiibaelghamry** [comment]
This is the intended flow, it is not a bug

**Comment by markarsanious** [comment]
Okay , but even no messages about successful registration is given. And i thought the regular flow, like any other website, should redirect to the login page to verify the password that you entered but it is okay if you intended the other flow

**Comment by alaa-megahed** [comment]
No need to show message as the navbar changes to show the "my profile" option instead of "signup" and "login".
We find this flow logical, more convenient for users and many websites have the same flow.
