### ISSUE TITLE
View Reservations 

### ISSUE THREAD

**Issue by markarsanious** [SEGUC17/Drop-The-Bit#23]
Severity: Medium
Reported By: Mark Isaac
Description: As a logged in student, I don’t have an option on the website to view my already made reservations and their status
Steps to release the issue: home>>login>>
Expected: I should have the option to view my already made reservations with their details and status (whether paid or not and the reservation info details)

**Comment by habiibaelghamry** [comment]
You will find in you profile.

**Comment by markarsanious** [comment]
Okay , yeah I found it. thank you
However, nothing shows the status whether i paid or i just booked to pay later.
