### ISSUE TITLE
Using Ejs file in the backend 

### ISSUE THREAD

**Issue by alaahatem** [SEGUC17/Drop-The-Bit#27]
Severity : High

Description : Ejs rendering appear in the backend controllers which should not happen 

Steps : In the code Angular/apps/controller/ AuthController as an example .

Expected : No rendering to ejs files , front end should all be handled by the front end framework

**Comment by radwasherif** [comment]
The routes sending EJS files are never used. We will remove the lines. The front end is thus entirely an AngularJS applications.
