### ISSUE TITLE
No Schedule in businesses' profiles

### ISSUE THREAD

**Issue by alaahatem** [SEGUC17/Drop-The-Bit#29]
Severity : Low 

Description : Nothing appear when any business’ schedule is clicked on whether it's not handled or no business did add a schedule yet .

Steps :Home> view all> choose any business > scroll down > click on view schedule 

Expected : A schedule to appear.

**Comment by alaa-megahed** [comment]
Please reload the page, it should appear!
We will try to enhance the flow to avoid the need to reload

**Comment by alaahatem** [comment]
yes,thank you but how should i login as an admin or service provider
 ?

**Comment by habiibaelghamry** [comment]
We enter a web admin we can send you its username and password and you can log in normally, the web admin adds the business and an email is sent to the business with the business's username and password then the business can log in normally.

**Comment by alaahatem** [comment]
Please provide me with the credentials.
