### ISSUE TITLE
Response Json objects

### ISSUE THREAD

**Issue by markarsanious** [SEGUC17/Drop-The-Bit#30]
Severity: Low
Reported By: Mark Isaac
Description: In the code on the repo, The res.status(200).send messages don't return a JSON object with a message and data , it just returns a string message or the javascript object not a json object with a consistent format.
Steps: api controllers
Expected: It should return a consistent response with a json object that has a message and data to be handled by the front end

**Comment by alaa-megahed** [comment]
Simply, if no data needed in the frontend we don't send them!
JSON object contains data when needed

**Comment by markarsanious** [comment]
in booking controllers, there was booking data sent but not as JSON object format
