### ISSUE TITLE
Email Validation of Register 

### ISSUE THREAD

**Issue by ahmedash11** [SEGUC17/Drop-The-Bit#33]
Severity : medium
By  Ahmed Kamal
Description : email validations are not complete , a user can register with an email of (????@live for example ) . Without putting the .com or with invalid characters for an email. It will login and you can start using the website without any form of validations.
Steps :home>> Signup
Expected : invalid email address .

**Comment by fshafik** [comment]
As long as the email follows correct email format, xx@xxx, it is accepted. We rely on the user's ability to enter his/her own email correctly.
