### ISSUE TITLE
Lag of registration submission

### ISSUE THREAD

**Issue by ahmelkady** [SEGUC17/Drop-The-Bit#37]
Severity: Low
By: Ahmed El Kady
Description: When you submit the registeration form, the website will freeze for sometime (long enough) for the user to doubt with no messages or any signs that it is still processing or loading

Steps: home>>signup>>submit

Expected: The browser page is shown still loading or a message is processed or shown loading.

**Comment by habiibaelghamry** [comment]
The website is a bit slow, we are working on enhancing this.
