### ISSUE TITLE
BusinessSchema Model

### ISSUE THREAD

**Issue by alaahatem** [SEGUC17/Drop-The-Bit#39]
Severity : Medium

Description : Email is not unique , does that mean that two different businesses with different usernames of course can have the same email? 

Steps : In the code, Api/apps/models/BookingSchema

Expected : the Email should be strictly unique

**Comment by alaa-megahed** [comment]
Nope, it's actually unique and we do the checks when adding new business to prevent inserting used mail.
This was just for the sake of testing(to be able to add many businesses).
But we will fix this.

**Comment by alaahatem** [comment]
Great

**Comment by alaa-megahed** [comment]
It's done now.
