### ISSUE TITLE
The booking Scenario

### ISSUE THREAD

**Issue by alaahatem** [SEGUC17/Drop-The-Bit#40]
Severity : High

Description : when i click book and pay now nothing happens  .

Steps : Search Kidzania , click check facilities >> click book now >>provide info >>> click book now

Expected : Booking form or payement form.

**Comment by NourhanKhaled** [comment]
Are you logged in?

**Comment by alaa-megahed** [comment]
Have you choose a valid time slot?

**Comment by alaahatem** [comment]
![rsz_screenshot_from_2017-05-01_20-20-18](https://cloud.githubusercontent.com/assets/25348490/25589275/4bc788d2-2eac-11e7-9e89-ecd9ef61bcf5.png)

**Comment by alaahatem** [comment]
![rsz_screenshot_from_2017-05-01_20-20-18](https://cloud.githubusercontent.com/assets/25348490/25589311/6c0014de-2eac-11e7-9655-be9841929de7.png)

**Comment by NourhanKhaled** [comment]
Does it work with 6? If yes then we'll fix the boundary condition now.

**Comment by alaahatem** [comment]
No , not even with 1, the problem is not with the boundary condition i believe  , i get an error in  the console concerning the function itself .(Error to load)

**Comment by NourhanKhaled** [comment]
I just tried it now and it redirects to a success route, could you please give it a try again?

**Comment by alaahatem** [comment]
yes it did work now , maybe the server was not consistent .
