### ISSUE TITLE
SEARCH BAR Not descriptive

### ISSUE THREAD

**Issue by AliWaleed97** [SEGUC17/Drop-The-Bit#43]
Severity: Low
By: Ali Waleed
Description: It is too general search box without any descriptive messages for the user on which
info should he/she enter to search by. Name or description or its offers or what
Steps: home>>login>>search
Expected: The placeholder of the search or any label should exist to the user to know what info
to include in the search

**Comment by NourhanKhaled** [comment]
You can search by anything and everything, sort by rating, area, name, filter by category area or minimum rating.
