### ISSUE TITLE
FOURTEENTH ISSUE Confirm PASSWORD MISSING

### ISSUE THREAD

**Issue by AliWaleed97** [SEGUC17/Drop-The-Bit#44]
Severity: Low
By: Ali Waleed
Description: When I’m signing up , no option to enter the password again to check that they are
equal to make sure before creating an account with a password that might have been entered
by mistake and the user will not be able to sign with it again.
Steps: home>>signUp
Expected: confirm password input in registration form

**Comment by habiibaelghamry** [comment]
Simply this is our design. A user can reset a password if he forgot it.
