### ISSUE TITLE
Business has the option to book his own facility

### ISSUE THREAD

**Issue by markarsanious** [SEGUC17/Drop-The-Bit#48]
Severity: Medium
By: Amr Hatem
Description: I created a facility then i found that i have the option to book it.
Steps: home>>login(with a business account)>>Check our facilities>>Book now
Expected: Book now button shouldn’t be there for Service providers (businesses)

**Comment by NourhanKhaled** [comment]
@markarsanious yes this is actually a feature for the business since some of the clients would want to book over phone or on site so we want the business to be able to add that to their bookings on the system.
