### ISSUE TITLE
Home page lags

### ISSUE THREAD

**Issue by markarsanious** [SEGUC17/Drop-The-Bit#49]
Severity: Low
By: Mark Isaac
Description: I signed in as Service provider, everytime I navigate to the home page, the whole website freezes for about a minute with no alerts or indications that it is loading , it just freezes
Steps: home>>login(with a business account)>>My Bisiness Plan Page>>home
Expected: A quicker user response or at least any indication that the page is loading

**Comment by fshafik** [comment]
This is already mentioned in another open issue, and we have already mentioned that the website experiences lagging.
