### ISSUE TITLE
Upload Image wrong size

### ISSUE THREAD

**Issue by markarsanious** [SEGUC17/Drop-The-Bit#50]
Severity: Low
By: Mark Isaac
Description: I signed in as Service provider, I tried to add an image to my business page, it doesn’t give me a success message upon upload and when it get uploaded, i found the pic zoomed in so half the image is not shown. I tried it with multiple images. 
Steps: home>>login(with a business account)>>My Bisiness Plan Page>>add Image>>upload an image
Expected: The image slider should be able to respond to the image size displaying all of it.

**Comment by yasmineamr** [comment]
The image is cropped if you uploaded a large image as the images at the slider are fixed sized.
