### ISSUE TITLE
Upload wrong Image formats

### ISSUE THREAD

**Issue by markarsanious** [SEGUC17/Drop-The-Bit#51]
Severity: Medium
By: Mark Isaac
Description: I signed in as Service provider, i navigated to my business page, I tried to upload a text file with csv extension , it didn’t give me any error and I found that it was uploaded and appeared as a broken image in the image slider.
Steps: home>>login(with a business account)>>My Bisiness Plan Page>>add image>>> choose file>>(upload any txt files)
Expected: I should get an error message that this file is not an image, please upload an image.

**Comment by habiibaelghamry** [comment]
This was mentioned before, can you stop duplicating the issues?
