### ISSUE TITLE
Delete Image missing alerts/ validation upon success

### ISSUE THREAD

**Issue by markarsanious** [SEGUC17/Drop-The-Bit#52]
Severity: Medium
By: Mark Isaac
Description: I signed in as Service provider, i navigated to my business page, I tried to delete an image from the image slider, I pressed a confirmation to delete it but then I got no response upon successful completion of deleting the image. I was not notified that the image was deleted. 

Steps: home>>login(with a business account)>>My Bisiness Plan Page>>delete image>>> yes

Expected: I should get an success message that this image was delete/an error message if deletion was not successful

**Comment by habiibaelghamry** [comment]
The image is deleted automatically, there is no need for a confirmation message.
