### ISSUE TITLE
EDITING PROFILE VIEW 

### ISSUE THREAD

**Issue by bassemawhoob** [SEGUC17/Drop-The-Bit#56]
Severity: Low
By: Bassem Mawhoob
Description: When editing profile for any user, I can’t see my old info so that I just modify it. I must write all the info again so it will be irritating for the user especially editing long texts like description (for a business) or address.

Steps: home>>login>>my profile>>edit profile
Expected: I should see my old info in the text boxes to just modify it and update them back.

**Comment by habiibaelghamry** [comment]
You write the info that you want to update only!
