### ISSUE TITLE
EDITING PROFILE Authority

### ISSUE THREAD

**Issue by bassemawhoob** [SEGUC17/Drop-The-Bit#57]
Severity: High
By: Bassem Mawhoob

Description: When editing profile for any user, I can modify everything even if it is crucial and should not be modified like the email (especially if it is the primary one) 

Steps: home>>login>>my profile>>edit profile
Expected: Either I should not have the option to edit my identifying info like the email unless i added another one.

**Comment by habiibaelghamry** [comment]
Why would not you be allowed to modify your email???
